### ISSUE TITLE
Item frames can turn invisible again (without smoke particle)

### ISSUE THREAD

**Issue by midamultitool** [origami-games/invisible-item-frames#2]
If you place any other item then cobble stone on the same block as the item frame (rails tripwire hook lever torch etc.) It will plop the item off but the item frame will remain invisible, only issue is once you remove the item from the invisible item frame it will still remain invisible in that situation.

**Comment by midamultitool** [comment]
This video is made in a fresh 1.16.2 world; https://vimeo.com/454963167

**Comment by dvitski** [comment]
Thanks for reporting this 🙂
